/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Light theme tokens
        "surface-tint": "#004ced",
        "on-primary-container": "#dfe3ff",
        "inverse-primary": "#b7c4ff",
        "surface-variant": "#dae2fd",
        "primary-fixed-dim": "#b7c4ff",
        "secondary": "#00687a",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "on-secondary": "#ffffff",
        "on-background": "#131b2e",
        "secondary-fixed": "#adecff",
        "on-surface": "#131b2e",
        "on-primary-fixed-variant": "#0038b6",
        "on-secondary-fixed-variant": "#004e5d",
        "surface-container": "#eaedff",
        "primary-container": "#0052ff",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "surface-container-low": "#f2f3ff",
        "on-tertiary-container": "#d6e6ff",
        "on-surface-variant": "#434656",
        "tertiary": "#3f4f65",
        "surface-container-highest": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "outline": "#737688",
        "surface-bright": "#faf8ff",
        "secondary-container": "#6ae1ff",
        "surface-dim": "#d2d9f4",
        "primary": "#003ec7",
        "surface": "#faf8ff",
        "tertiary-container": "#57677e",
        "surface-container-high": "#e2e7ff",
        "on-secondary-container": "#006374",
        "primary-fixed": "#dde1ff",
        "background": "#faf8ff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#d3e4fe",
        "secondary-fixed-dim": "#5dd6f3",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#001452",
        "tertiary-fixed-dim": "#b7c8e1",
        "outline-variant": "#c3c5d9",
        "error-container": "#ffdad6",
        // Dark theme extras
        "dark-background": "#0b1326",
        "dark-surface": "#0b1326",
        "dark-surface-container": "#171f33",
        "dark-surface-container-high": "#222a3d",
        "dark-surface-container-highest": "#2d3449",
        "dark-on-surface": "#dae2fd",
        "dark-primary": "#b4c5ff",
        "dark-primary-container": "#0062ff",
        "dark-secondary": "#a6e6ff",
        "dark-secondary-container": "#14d1ff",
        "dark-tertiary": "#d0bcff",
        "dark-outline": "#8c90a2",
        "dark-outline-variant": "#424656",
        "dark-on-surface-variant": "#c2c6d9",
        "dark-error": "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        md: "24px",
        lg: "40px",
        "container-max": "1440px",
        xl: "64px",
        base: "8px",
        xs: "4px",
        "margin-mobile": "16px",
        sm: "12px",
        "margin-desktop": "48px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "data-tabular": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};